FROM python:3.8.0-slim
LABEL maintainer="Lanjelin"
RUN export DEBIAN_FRONTEND=noninteractive; \
    apt-get update && \
    apt-get install -y wget && \
    wget -qO /watcher.py https://raw.githubusercontent.com/Lanjelin/VPNWatch/main/Watcher/watcher.py && \
    wget -qO /requirements.txt https://raw.githubusercontent.com/Lanjelin/VPNWatch/main/Watcher/requirements.txt && \
    chmod +x watcher.py && \
    python3 -m pip install -r requirements.txt
ENTRYPOINT ["python3", "/watcher.py"]
